name: 'SherlockQA-AI'
description: 'AI-powered code review and QA that finds bugs, security issues, and suggests test scenarios'
author: 'mayurrawte'

branding:
  icon: 'search'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  # AI Provider
  ai-provider:
    description: 'AI provider to use (openai, azure, azure-responses)'
    required: false
    default: 'openai'

  # OpenAI Configuration
  openai-api-key:
    description: 'OpenAI API key'
    required: false
  model:
    description: 'Model to use for review'
    required: false
    default: 'gpt-4'

  # Azure OpenAI Configuration
  azure-api-key:
    description: 'Azure OpenAI API key'
    required: false
  azure-endpoint:
    description: 'Azure OpenAI endpoint URL (e.g., https://your-resource.openai.azure.com)'
    required: false
  azure-deployment:
    description: 'Azure OpenAI deployment name'
    required: false
  azure-api-version:
    description: 'Azure OpenAI API version'
    required: false
    default: '2024-02-15-preview'

  # Review Configuration
  min-severity:
    description: 'Minimum severity to report (error, warning, suggestion)'
    required: false
    default: 'warning'
  ignore-patterns:
    description: 'Comma-separated list of file patterns to ignore'
    required: false
    default: '*.md,*.txt,package-lock.json,yarn.lock'

  # Custom Prompts
  persona:
    description: 'Custom persona/role instructions (e.g., "Act as a senior security engineer")'
    required: false
  domain-knowledge:
    description: 'Domain-specific context for better reviews (e.g., freight forwarding, e-commerce)'
    required: false

  # Max tokens for response
  max-tokens:
    description: 'Maximum tokens for AI response'
    required: false
    default: '4096'

  # Approval Configuration
  auto-approve:
    description: 'Submit APPROVE when verdict is approved (requires PAT or repo settings to allow Actions to approve PRs)'
    required: false
    default: 'false'

  # Code Quality Analysis
  code-quality:
    description: 'Enable code quality analysis (checks for repetitive code, code smells, maintainability issues)'
    required: false
    default: 'false'

outputs:
  verdict:
    description: 'Review verdict (approved, needs_changes, do_not_merge)'
  summary:
    description: 'Review summary'
  issues-count:
    description: 'Number of issues found'

runs:
  using: 'node20'
  main: 'dist/index.js'
